# site configuration
title: "Kelly J Andrewws"
baseurl: "http://kellyjandrews.github.io/"
repo: "https://github.com/kellyjandrews/kellyjandrews.github.io/"
branch: "tree/gh-pages/"
quiet:    true

github: "https://github.com/kellyjandrews"
twitter: "https://twitter.com/kellyjandrews"
linkedin: "https://www.linkedin.com/in/kjandrews/en"
stackexchange: "https://stackexchange.com/users/2222625/kelly-j-andrews"

# Where things are
source:      .
destination: ./_site
plugins:     ./_plugins
posts:       ./_posts
pages:       ./_pages
layouts:     ./_layouts
data_source: ./_data
collections: null

# Conversion
markdown:    kramdown
highlighter: pygments
excerpt_separator: "<!-- more -->"

# Handling Reading
exclude: ["less","gulp","node_modules","Gulpfile.js","package.json","scripts"]
include: ["_pages"]
encoding: "utf-8"

defaults:
  -
    scope:
      path: "" # empty string for all files
      type: "posts"
    values:
      layout: "post"
